name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build

      - run: pipx install poetry
        if: runner.os == 'Windows'
      - run: brew install poetry
        if: runner.os == 'macOS'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: poetry install
      - run: poetry run poe -q release
      - uses: actions/upload-artifact@v3
        with:
          name: archives
          path: dist/*.zip

  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: archives
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: "${{ contains(github.ref, 'draft') }}"
          files: |
            *.zip
